version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: express-api:latest
    container_name: express-api-container
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: 'production'
      # postgresql://username:password@host:port/database
      DATABASE_URL: 'postgresql://postgres:123456@db:5432/petinder_db'
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - ./app:/app
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: "123456" # Make sure this matches the password in Sequelize
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db-scripts:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
volumes:
  postgres_data:
