version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: express-api:latest
    container_name: express-api-container
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: 'production'
      DATABASE_URL: 'postgresql://postgres:password@db:5432/postgres'
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
