name: Build and Push Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker Compose
      run: |
        docker-compose build
        docker-compose push
      env:
        DOCKER_USERNAME: ${{ github.h0u554m }}
        DOCKER_PASSWORD: ${{ secrets.hp_3Gtk3Pva5EaBeSXTZxLVFTGpbzjxEZ19pULO }}
