name: Build and Push Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker Compose
        uses: adrielcodeco/docker-compose-run-action@v1
        with:
          compose-file: "docker-compose.yml"
          service: services
          run: build

      - name: Push Docker Compose images
        uses: adrielcodeco/docker-compose-run-action@v1
        with:
          compose-file: "docker-compose.yml"
          service: services
          run: push
